### DISCUSSION TITLE
Move Home Assistant actions to a file

### DISCUSSION THREAD

**Discussion by nerdaxic** [nerdaxic/glados-voice-assistant#5] [Show and tell]
Idea is to take hard-coded Home Assistant actions into json file to make system more dynamic.
Looking for suggestions for the structure of the json file and smart way to parse it.

**Comment by nerdaxic** [comment]
Suggestion for structure of YAML file to configure Home Assistant actions on the voice assistant's side:
```YAML
# Server related settings
api:
  address: "192.168.1.221"
  key: "1234"

# The weather entity settings to get forecasts etc
weather:
  entity: "weather.home"

# Allow setting of volume level from Home Assistant
volume:
  entity: "input_number.glados_volume"

# Allow mute of the mic automatically (player playing etc.)
mute:
  entity: "input_boolean.glados_microphone"

# All light configurations
lights:
  light_group:
   command: "turn $on_off $room lights", "set $room lights $light_state"
   entity: "group.$room_lights"
   response: "I have turned $on_off the lights in the $room", "$room lights are now $on_off"

  light:
    command: "turn $on_off test lamp","set test lamp $color"
    entity: "light.test_lamp"
    # response missing for test purposes

# All script configurations
scripts:
  script:
  	command: "turn on home cinema", "turn on cinema"
  	entity: "script.start_cinema"
  	response: "okay, fine", "give me a moment"

  script:
    command: "good bye", "I'm leaving"
    entity: "script.away_mode"
    response: "bye", "now I only want you gone"

  # Run scripts with GLaDOS internal triggers
  start_listening:
    entity: "script.glados_start_listening_script"

  stop_listening:
    entity: "script.glados_stop_listening_script"

  start_speaking:
    entity: "script.glados_start_speaking_script"

  stop_speaking:
    entity: "script.glados_stop_speaking_script"

# Examples for variables
# on_off        "on" | "off"
# room          "living room" | "bedroom" | "bathroom"
# light_state   "92 procent" | "green" | "half brightness"
```
